# Generated by Django 4.2.2 on 2023-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_cellline_plasmids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellline',
            name='plasmids',
            field=models.ManyToManyField(blank=True, to='sample.plasmid'),
        ),
    ]
