# Generated by Django 4.2.2 on 2023-07-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_alter_cellline_plasmids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmid',
            name='sequence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.cellline'),
        ),
    ]
