# Generated by Django 4.2.2 on 2023-07-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_alter_plasmid_sequence_alter_protein_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellline',
            old_name='plasmids',
            new_name='_plasmids',
        ),
        migrations.RenameField(
            model_name='plasmid',
            old_name='sequence',
            new_name='_sequence',
        ),
        migrations.RenameField(
            model_name='protein',
            old_name='host',
            new_name='_host',
        ),
    ]
